language: csharp
mono: none
node_js: '10'
os: linux
dotnet: 2.1.300
dist: trusty
group: stable
cache: npm
install:
  - nvm install 10.3.0
  - nvm use 10.3.0
  - npm install

addons:
  apt:
    packages:
      - libxml2-utils # for `xmllint`.

jobs:
  include:
    #- stage: node-test
    #  script: npm run test -s

    - stage: dotnet-test
      script: dotnet test tests/SWISSRETS.Tests.csproj

    - stage: update gh-pages
      script: npm run update-pages -s
