language: node_js
node_js: '10'
os: linux
dist: trusty
group: stable
cache: npm
addons:
  apt:
    packages:
      - libxml2-utils # for `xmllint`.

jobs:
  include:
    - stage: test
      script: npm run test -s

    - stage: update wiki pages
      script: npm run fetch-wiki
