language: node_js
node_js: '10'
os: linux
dotnet: 2.1.300
dist: trusty
group: stable
cache: npm
install:
  - dotnet restore

addons:
  apt:
    packages:
      - libxml2-utils # for `xmllint`.

jobs:
  include:
    - stage: test
      script: echo dotnet test tests/SWISSRETS.Tests.csproj and npm run test -s

    - stage: update gh-pages
      script: npm run update-pages -s
