os: linux
dist: trusty
group: stable
language: java
addons:
  apt:
    packages:
      - libxml2-utils # for `xmllint`.
script:
  - xmllint --version
  - xmllint --noout --schema ./schema/schema.xsd ./examples/example.xml
