os: linux
dist: trusty
group: stable
language: java
addons:
  apt:
    packages:
      - libxml2-utils # for `xmllint`.
jobs:  
  include:
    - stage: System info
      script: xmllint --version

    - stage: Schema validation
      script:
        - curl https://www.w3.org/2001/XMLSchema.xsd > _tmp.xsd
        - xmllint --noout --schema _tmp.xsd ./schema/schema.xsd
        - rm _tmp.xsd

    - stage: Example validation
      script: xmllint --noout --schema ./schema/schema.xsd ./docs/example.xml
