os: linux
dist: trusty
group: stable

language: csharp
mono: none
dotnet: 2.1.300
node_js: '10'
cache: npm

install:
  - nvm install node
  - nvm use node
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test -s

    - if: branch = master
      stage: update gh-pages
      script: npm run update-pages -s
