os: linux
dist: trusty
group: stable
language: java
addons:
  apt:
    packages:
      - libxml2-utils # for `xmllint`.
script:
  - xmllint --version
  - curl https://www.w3.org/2001/XMLSchema.xsd > _tmp.xsd
  - xmllint --noout --schema _tmp.xsd ./schema/schema.xsd
  - xmllint --noout --schema ./schema/schema.xsd ./docs/example.xml
