name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
    - run: npm run lint
