name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint full.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./examples/full.xml
        xml-schema-file: ./schema/schema.xsd
    - name: Lint minimal.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./examples/minimal.xml
        xml-schema-file: ./schema/schema.xsd
    - name: Lint multiple.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./examples/multiple.xml
        xml-schema-file: ./schema/schema.xsd
  xsd-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
    - name: build xsddoc static files
      run: npm run xsddoc
    - name: commit xsddoc into documentation
      uses: EndBug/add-and-commit@v6
      with:
        add: 'docs/docs'
        author_name: 'xsddoc'
        message: 'Build of new xsddocs from a GitHub action'
